### ISSUE TITLE
App crashes with following error

### ISSUE THREAD

**Issue by gaurav3017** [MAXDeliveryNG/slideview#7]
java.lang.ClassCastException: ng.max.slideview.Slider cannot be cast to ng.max.slideview.SlideView

**Comment by kizitonwose** [comment]
Why are you casting the Slider class as SlideView? The cast will always fail. Can you share some code so I can understand what you're trying to do?

**Comment by aryo** [comment]
Probably due to this line in the readme:
```SlideView slideView = (SlideView) findViewById(R.id.slider);```
when trying to set the onSlideComplete listener.

When he should be using _his_ SlideView instance's id (`R.id.slider` is the id of the Slider within a SlideView).
